### ISSUE TITLE
Sasha's first work items (todo in backlog grooming) WRONG REPO

### ISSUE THREAD

**Issue by defuse** [zcash/zcash-gitian#114]
Environment setup:

- [x] Get the iOS ECC internal wallet from testflight
- [x] Use zcashd
- [x] Compile zcashd
- [x] Get slack set up on phone
- [x] Get new yubikey set up
- [ ] Run lightwalletd via a Docker container
- [ ] Spin up zcashd in GCP
- [ ] Go over security policy documents

Project ideas:

- [ ] Run zcash smoke tests
- [ ] Help run a release
- Deploy fuzzers (as an intro to k8s)
- Dependency alert script -> slack
- Fix #wordpress login alert bot
- Fix banhalen
- Pair on fixing the zcashd fuzzer
- Pull certirficate transparency database to look for zcash scams
- Test backup options (spideroak)

(early preference for stuff where procedures are already done + stuff built out of nothing.)
