### ISSUE TITLE
DO2-Q3-2020: Provide examples of what dev-infra does to the community

### ISSUE THREAD

**Issue by torizoemitchell** [zcash/zcash-gitian#93]
Key Results: 

- [ ] DOKR2a: Conduct a public mega lab

- [ ] DOKR2b: Have 5 humans sign up for dev-infra lab

- [ ] DOKR2c: Create new documentation with doc team to help simplify spinning up zcash components.

(reduce time from landing to current height)
